### PR TITLE
Added Foss Profile

### PR DESCRIPTION
**Pull request by jrtechs**
Hey guys, I finally got around to creating my FOSS profile.

### CODE REVIEW

**Comment by Tjzabel** [comment]
@jrtechs you have to shorten your bio :stuck_out_tongue: 

It needs to be < 80 chars

**Comment by jrtechs** [comment]
The template said it had to be under 140.

**Comment by jwflory** [comment]
Hi @jrtechs, good catch. I fixed the CI to be less picky in commit dfe7e658a0d399484c464ecc5f0db481772a831a. Could you please pull in latest commits from `master` and try again?

**Comment by jrtechs** [comment]
Thanks @jwflory! I just updated this branch.

**Pull request merged**
